/**
  ******************************************************************************
  * @file		init.c
  * @author		Przekaï¿½nik elektroniczny
  * @version	V1.0.0
  * @date		17.12.2014
  * @brief		This file contains the system clock configuration for STM32L1xx
  * 			High-density devices, and is generated by the Michaï¿½ Szczygieï¿½
  *             
  * 1.  This file provides two functions and one global variable to be called from 
  *     user application:
  *      - Init_RCC(): 
  *                        
  *      - Init_IO():
  *
  *      - Init_Peripherals():
  * 
  * 2. This file configures the system clock as follows:  
  *=============================================================================
  *                         System Clock Configuration
  *=============================================================================
  *        System Clock source          | PLL(HSE)
  *----------------------------------------------------------------------------- 
  *        SYSCLK                       | 32 MHz
  *----------------------------------------------------------------------------- 
  *        HCLK                         | 32 MHz
  *----------------------------------------------------------------------------- 
  *        AHB Prescaler                | 1
  *----------------------------------------------------------------------------- 
  *        APB1 Prescaler               | 1
  *----------------------------------------------------------------------------- 
  *        APB2 Prescaler               | 1
  *----------------------------------------------------------------------------- 
  *        HSE Frequency                | 4 MHz
  *----------------------------------------------------------------------------- 
  *        PLL DIV                      | 2
  *----------------------------------------------------------------------------- 
  *        PLL MUL                      | 16
  *----------------------------------------------------------------------------- 
  *        VDD                          | 3.3 V
  *----------------------------------------------------------------------------- 
  *        Vcore                        | 1.8 V (Range 1)
  *----------------------------------------------------------------------------- 
  *        Flash Latency                | 1 WS
  *----------------------------------------------------------------------------- 
  *        Require 48MHz for USB clock  | Enable
  *----------------------------------------------------------------------------- 
  *=============================================================================
  ******************************************************************************  
  */

#include <stdio.h>
#include "main.h"
#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "..\StdPeriph_Driver\inc\misc.h"
#include "..\StdPeriph_Driver\inc\stm32f10x_adc.h"
#include "..\peripherals\timer\timer.h"
#include "..\peripherals\uart\uart.h"
#include "..\peripherals\adc\adc.h"
#include "..\peripherals\exti\exti.h"
#include "..\peripherals\iwdg\iwdg.h"
#include "..\setup\setup.h"
#include "..\board\init.h"
#include "..\board\board_v_26_02_2017.h"

unsigned int i_nom, mull;
unsigned char i, tmp;

/**
 ******************************************************************************
  [..] RCC Referense Manual ST32F10x
 *
 *  @brief Init_RCC
 */
void Init_RCC(void)
{  
	/** W³¹czenie zasilania interfejsu zegara */
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_PWREN);

	MODIFY_REG(RCC->CFGR, RCC_CFGR_PLLSRC, RCC_CFGR_PLLSRC_HSE);  // wybór HSE jako Ÿród³a PLL bez dzielnika

	/** W³¹cz Kwarc */
	SET_BIT(RCC->CR, RCC_CR_HSEON);
	while(!(RCC->CR & RCC_CR_HSERDY)){}

	/** W³¹cz PLL */
	SET_BIT(RCC->CR, RCC_CR_PLLON);
	while(!(RCC->CR & RCC_CR_PLLRDY)){}

	/** SYS_CLK 72 MHz*/ // - aktualne

	/** Prze³¹cz zegar systemowy na PLL */
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_PLL);
	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL){}       // SprawdŸ czy PLL OK

	MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE,  RCC_CFGR_HPRE_DIV1);    // AHB  /1  magistrala systemowa HCLK = 72MHz Systick = 4000
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1, RCC_CFGR_PPRE1_DIV2);   // APB1 /2  magistrala peryferiï¿½w PCLK1 = 36MHz
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE2, RCC_CFGR_PPRE2_DIV1);   // APB2 /1  magistrala peryferiï¿½w PCLK2 = 32MHz
}

#if defined ( MEARM_BOARD_V_26_02_2017_H)

//
// \brief Platform Board 26.02.2017
//
void Init_IO(void)
{
//	PORT u¿yte w projekcie
//	PA0 - PA12, PA15,
//	PB0, PB1, PB3 - PB15
//	PC13 - PC15

//	PORT-A ----------------------------------------------------------------------------------------------------------
//	GPIO port A clock enable
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPAEN);

//	CRL
//	  0		PA0	-	ADC0	-	Pomiar wartoœci potencometru
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE0, 0);	// ANALOG INPUT
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF0, 0); 	// ANALOG INPUT
//	  1		PA1	-	ACD1	-	Pomiar wartoœci potencometru
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE1, 0);	// ANALOG INPUT
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF1, 0);	// ANALOG INPUT
//    2		PA2	-	ADC2	-	Pomiar wartoœci potencometru
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE2, 0);	// ANALOG INPUT
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF2, 0);	// ANALOG INPUT
//	  3		PA3	-	ADC3	-	Pomiar wartoœci potencometru
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE3, 0);	// ANALOG INPUT
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF3, 0);	// ANALOG INPUT
//	  4		PA4	-	ADC4	-	Pomiar wartoœci potencometru
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE4, 0);	// ANALOG INPUT
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF4, 0);	// ANALOG INPUT
//	  5		PA5	-	SPI_SCK	-	LED WS2812B
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE5, GPIO_CRL_MODE5_0); // SPI1_SCK Output pin 10MHz
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF5, GPIO_CRL_CNF5_1);	// Alternate function push-pull
//	  6		PA6	-	SPI_MISO-	LED WS2812B
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE6, 0); // SPI1_MISO Input
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF6, GPIO_CRL_CNF6_1);	// 	Input floating / Input pull-up
//	  7		PA7	-	SPI_MOSI-	LED WS2812B
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE7, GPIO_CRL_MODE7_0); // SPI1_MOSI Output pin 10MHz
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_CNF7, GPIO_CRL_CNF7_1);	// Alternate function push-pull

//	CRH
//	  8		PA8		-	Nie u¿ywane
//	  9		PA9		-	USART1_TX
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE9, GPIO_CRH_MODE9_0); //wejœcie USART1_TX Output pin 10MHz
	MODIFY_REG(GPIOA->CRL, GPIO_CRH_CNF9, GPIO_CRH_CNF9_1);	// Alternate function push-pull
//	 10		PA10	-	USART1_RX
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE10, 0); // USART_RX Input pin
	MODIFY_REG(GPIOA->CRL, GPIO_CRH_CNF10, GPIO_CRH_CNF9_1);	// Input floating / Input pull-up
//	 11		PA11	-	USB_DM	-	Aktualnie nie u¿ywane
//	 12		PA12	-	USB_DP	-	Aktualnie nie u¿ywane
//	 13		PA13	-	SWDIO
//	 14		PA14	-	SWCLK
//	 15		PA15	-	Nie u¿ywane

//	 PORT-B ----------------------------------------------------------------------------------------------------------
//	GPIO port B clock enable
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN);

//	CRL
//	  0   	PB0	-	Nie u¿ywane
//	  1		PB1	-	Nie u¿ywane
//    2		PB2	-	Nie u¿ywane
//	  3		PB3	-	Nie u¿ywane
//	  4		PB4	-	Nie u¿ywane
//	  5		PB5	-	Nie u¿ywane
//	  6		PB6	-	Nie u¿ywane
	MODIFY_REG(GPIOB->CRL, GPIO_CRL_MODE6, GPIO_CRL_MODE6_0); // PWM Output pin 10MHz
	MODIFY_REG(GPIOB->CRL, GPIO_CRL_CNF6, GPIO_CRL_CNF6_1);	// Alternate function push-pull
//	  7		PB7	-	Nie u¿ywane
	MODIFY_REG(GPIOB->CRL, GPIO_CRL_MODE7, GPIO_CRL_MODE7_0); // PWM Output pin 10MHz
	MODIFY_REG(GPIOB->CRL, GPIO_CRL_CNF7, GPIO_CRL_CNF7_1);	// Alternate function push-pull

	//	CRH
//	  8		PB8	-	Nie u¿ywane
	MODIFY_REG(GPIOB->CRH, GPIO_CRH_MODE8, GPIO_CRH_MODE8_0); // PWM Output pin 10MHz
	MODIFY_REG(GPIOB->CRH, GPIO_CRH_CNF8, GPIO_CRH_CNF8_1);	// Alternate function push-pull
//	  9		PB9	-	Nie u¿ywane
	MODIFY_REG(GPIOB->CRH, GPIO_CRH_MODE9, GPIO_CRH_MODE9_0); // PWM Output pin 10MHz
	MODIFY_REG(GPIOB->CRH, GPIO_CRH_CNF9, GPIO_CRH_CNF9_1);	// Alternate function push-pull
//	  10	PB10-	Nie u¿ywane
//	  11	PB11-	Nie u¿ywane
//	  12	PB12-	SPI_NSS	-	LCD
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE12, GPIO_CRH_MODE12_0); // SP21_NSS Output pin 10MHz
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_CNF12, GPIO_CRH_CNF12_1);	// Alternate function push-pull
//	  13		PB13	-	SPI_SCK	-	LCD
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE13, GPIO_CRH_MODE13_0); // SPI2_SCK Output pin 10MHz
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_CNF13, GPIO_CRH_CNF13_1);	// Alternate function push-pull
//	  14		PA14		-	SPI_MISO-	LCD
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE14, 0); 				// SPI2_MISO Input
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_CNF14, GPIO_CRH_CNF14_1);	// 	Input floating / Input pull-up
//	  15		PA15		-	SPI_MOSI-	LCD
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_MODE15, GPIO_CRH_MODE15_0); // SPI2_MOSI Output pin 10MHz
	MODIFY_REG(GPIOA->CRH, GPIO_CRH_CNF15, GPIO_CRH_CNF15_1);	// Alternate function push-pull

//	 PORT-C ----------------------------------------------------------------------------------------------------------
//	!< GPIO port C clock enable
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPCEN);

//	CRH
//	 13		PC13		-	LED na PCB NANO
	MODIFY_REG(GPIOC->CRH, GPIO_CRH_MODE13, GPIO_CRH_MODE13_0); // 10 Output pin 10MHz
//	 14		PC14		-	Nie u¿ywane
//	 15		PC15		-	Nie u¿ywane

//     END GPIO ----------------------------------------------------------------------------------------------------------

}
#endif // Board

void Init_Peripherals(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

	Init_Timer2();       // 1ms
	Init_PWMTimer();	// Generowanie sygna³u PWM na wyjœciach B0, B1, B4, B5
	InitUART1();        // Konsolka
	Init_IWDG();		// WatchDog
//	Init_ADC();
	InitEXTI();
}
